// Auto-generated by scripts/train-risk-model.mjs. Do not edit manually.

export interface TrainedHeartModelArtifact {
  featureNames: string[];
  means: number[];
  stds: number[];
  weights: number[];
  bias: number;
  metadata: {
    trainedAt: string;
    datasetRows: number;
    split: string;
    trainAccuracy: number;
    testAccuracy: number;
  };
}

export const trainedHeartModel: TrainedHeartModelArtifact = {
  "featureNames": [
    "Age",
    "RestingBP",
    "Cholesterol",
    "FastingBS"
  ],
  "means": [
    53.33651226158038,
    132.55040871934605,
    198.6716621253406,
    0.22479564032697547
  ],
  "stds": [
    9.388952394848848,
    18.47745643455063,
    109.35192961405089,
    0.41744767386698794
  ],
  "weights": [
    0.42983723635296245,
    0.10945815614336621,
    -0.4574163278955668,
    0.43231891976049613
  ],
  "bias": 0.30438930114437995,
  "metadata": {
    "trainedAt": "2026-03-29T07:46:22.839Z",
    "datasetRows": 918,
    "split": "80/20",
    "trainAccuracy": 0.6757,
    "testAccuracy": 0.6957
  }
} as const;
