// Auto-generated by scripts/train-risk-model.mjs. Do not edit manually.

export interface TrainedHeartModelArtifact {
  featureNames: string[];
  means: number[];
  stds: number[];
  weights: number[];
  bias: number;
  metadata: {
    trainedAt: string;
    datasetRows: number;
    split: string;
    trainAccuracy: number;
    testAccuracy: number;
  };
}

export const trainedHeartModel: TrainedHeartModelArtifact = {
  "featureNames": [
    "Age",
    "RestingBP",
    "Cholesterol",
    "FastingBS"
  ],
  "means": [
    53.33651226158038,
    132.55040871934605,
    198.6716621253406,
    0.22479564032697547
  ],
  "stds": [
    9.388952394848848,
    18.47745643455063,
    109.35192961405089,
    0.41744767386698794
  ],
  "weights": [
    0.092384994034734,
    0.0313658167771665,
    -0.0912584127276562,
    0.0965345727488775
  ],
  "bias": 0.0008712960090029815,
  "metadata": {
    "trainedAt": "2026-03-29T09:08:46.357Z",
    "datasetRows": 918,
    "split": "80/20",
    "trainAccuracy": 0.6403,
    "testAccuracy": 0.6739
  }
} as const;
