// Auto-generated by scripts/train-risk-model.mjs. Do not edit manually.

export interface TrainedHeartModelArtifact {
  featureNames: string[];
  means: number[];
  stds: number[];
  weights: number[];
  bias: number;
  metadata: {
    trainedAt: string;
    datasetRows: number;
    split: string;
    trainAccuracy: number;
    testAccuracy: number;
  };
}

export const trainedHeartModel: TrainedHeartModelArtifact = {
  "featureNames": [
    "Age",
    "BMI",
    "Smoking",
    "Diabetic",
    "PhysicalActivity",
    "SleepTime"
  ],
  "means": [
    54.38181230057785,
    28.276662966082984,
    0.4118229630487479,
    0.1304255803459113,
    0.7760960980148636,
    7.09932471017647
  ],
  "stds": [
    17.97898614109529,
    6.339629636708803,
    0.4921633978213794,
    0.3367710622034349,
    0.41685842280171304,
    1.4331412288598981
  ],
  "weights": [
    1.1125063292095374,
    0.16779804450367145,
    0.31469595245359894,
    0.31361161330617043,
    -0.1546151111452934,
    -0.08091215133195728
  ],
  "bias": -0.6267984744393359,
  "metadata": {
    "trainedAt": "2026-03-29T09:01:37.007Z",
    "datasetRows": 313014,
    "split": "80/20",
    "trainAccuracy": 0.6883,
    "testAccuracy": 0.6873
  }
} as const;
